### PR TITLE
Allow query on orml_tokens storage

### LINKED ISSUE #29: Add test and RPC calls(if needed) to query chain state
- [ ] USDv total supply and collaterals
- [ ] Rates by asset pair

### PR DESCRIPTION
**Pull request by stanly-johnson**
Resolves #29 
fix : Allow query on `orml_tokens` pallet storage. This will allow to query totalSupply of all tokens.

- [X] USDv total supply and collaterals
- [X] Rates by asset pair -> Already possible since `liquidity_provider` storage can be [queried](https://github.com/valibre-org/vln-node/blob/0faa06a2c42f49fec832741901a67f751d6bca06/runtime/src/lib.rs#L98)

### CODE REVIEW

**Comment by olanod** [comment]
Hi @stanly-johnson Thanks for the addition. If it's not much to ask, for https://github.com/valibre-org/vln-node/issues/29  ideally this would come as well with the client(substrate-subxt based) code to make those requests. Check on [`valiu-node-rpc`](https://github.com/valibre-org/vln-node/tree/master/valiu-node-rpc). Sorry it wasn't clear in the ticket.

**Comment by stanly-johnson** [comment]
I will continue to work on this after #32 is merged since that PR changes a lot related to valiu-node-rpc

**Comment by olanod** [comment]
> I will continue to work on this after #32 is merged since that PR includes a lot of changes to valiu-node-rpc

Sure thing, no problem :)

**Comment by stanly-johnson** [comment]
@olanod I've added the client code to query for total issuance. Can you take a look and confirm if this is what you are looking for. If so, I will add the liquidity provider query aswell.

**Comment by olanod** [comment]
Looking good! The total issuance call looks simple enough! :) could you rebase on top of latest master to have a better view?

**Review by olanod — APPROVED** [review]
Awesome! looks good 🚀  this can be merged already and the rates can be a separate PR :)

**Pull request merged**
